Update to HtmlUnit 2.50
HtmlUnit/NHtmlUnit pull request #37
Opened 2021-06-03 05:51 UTC by AlexanderStromer

As requested with #34 I took it into my own hands and updated. It works fine on my side. If also ok for you, consider updating NuGet as well, thx

Had to change the tests, since wikipedia has some SSL handshake issue when requesting the page (also did not work with v2.19)

2021-06-03 07:34 UTC, asbjornu commented
Awesome! 👏🏼 Could you please add a GitHub Action workflow as well, so we get some automated tests that prove everything is in working order? 🙏🏼

2021-06-04 00:52 UTC, AlexanderStromer commented
done, also did some badge-work for the readme
let me know your thoughts

2021-06-04 08:12 UTC, asbjornu requested changes
Great stuff!

2021-06-04 08:12 UTC, asbjornu commented on .github/workflows/unittests.yml
> +  runalltests:
```suggestion
  test:
```

2021-06-04 08:17 UTC, asbjornu approved these changes

2021-06-04 08:18 UTC, merged

2021-06-04 08:18 UTC, asbjornu commented
Thank you so much for this, @AlexanderStromer! 🙏🏼