NuGet publish
HtmlUnit/NHtmlUnit pull request #39
Opened 2021-06-04 17:37 UTC by AlexanderStromer

1. Manual Trigger of workflow (see Actions -> Nuget Publish)
2. All ready to go, **but** before you try to publish you need to setup the APIKey secret so you can publish to nuget:
  2a: In Nuget.org -> your name (top right) > API Keys -> Create new key and copy
  2b: In GitHub -> NHtmlUnit -> Settings -> Secrets (only visible to Contributors) -> Add a new secret called "NUGET_APIKEY" with the APIKey as value

2021-06-04 17:39 UTC, AlexanderStromer commented
wrt #38

2021-06-04 20:31 UTC, asbjornu requested changes
Brilliant!

2021-06-04 20:31 UTC, asbjornu commented on .github/workflows/nugetpublish.yml
> +      run: nuget push *.nupkg -Source nuget.org -ApiKey ${{ secrets.NuGet_APIKey }}
```suggestion
      run: nuget push *.nupkg -Source nuget.org -ApiKey ${{ secrets.NUGET_API_KEY }}
```

2021-06-04 20:34 UTC, asbjornu requested changes

2021-06-04 20:34 UTC, asbjornu commented on .github/workflows/nugetpublish.yml
> +on: workflow_dispatch
It would be great to release to NuGet when a release (and tag) is created on GitHub, so the only manual labour required would be to create the GitHub release. From it we also get the version number we can use for the NuGet package (so it no longer needs to be hard coded). [GitVersion](https://github.com/marketplace/actions/gittools) can assist in producing a version number from the created tag.

2021-06-05 07:47 UTC, AlexanderStromer commented on .github/workflows/nugetpublish.yml
> +on: workflow_dispatch
I thought about this and had a look at GitVersion. I think you already did a good job adopting the version of HtmlUnit for NHtmlUnit (assuming NHtmlUnit does not have its own releases as such, e.g. for fixes). Also, adopting this auto-versioning-workflow makes it a mixed bag of what is actually getting published/updated automatically. I'd prefer a simple straightforward approach, which is either
a. **all** version handling is done by GitHub workflows
b. **no** version handling is done by GitHub workflows
Since NHtmlUnit is highly dependent on HtmlUnit's version, which requires manual handling anyway, I would recommend option b
Simply put, given the mixed-bag outcome and effort to implement GitVersion, I don't think its worth it.

As for NuGet publish when making a GitHub release, this is easy to do, you can add similar as seen here >
[SharpZipLib Using Release](https://github.com/icsharpcode/SharpZipLib/blob/master/.github/workflows/release.yml)

2021-06-06 00:22 UTC, asbjornu commented on .github/workflows/nugetpublish.yml
> +on: workflow_dispatch
I'm not saying the version number should be minted automatically. I'm saying the version number manually minted when creating the release should be the version number stamped in the published `.nupkg` so we don't have to manually keep two version numbers in tight synchronization. Thinking about it, GitVersion isn't necessary since the we can just extract the version number directly from `github.ref`.

2021-06-06 01:00 UTC, AlexanderStromer commented on .github/workflows/nugetpublish.yml
> +on: workflow_dispatch
Looks like you know more about this than me :) I'll leave that for you.

2021-06-06 22:18 UTC, asbjornu commented
Thanks for moving this in the right direction, @AlexanderStromer! #40 and a few more PRs are now merged and [version 2.50.0 is now published on NuGet.org](https://www.nuget.org/packages/NHtmlUnit/2.50.0). 🎉

2021-06-06 22:18 UTC, closed without merging